# Directus Docs:
# https://directus.io/docs/self-hosting/deploying#docker-compose-examples
services:
  admin:
    image: directus/directus:latest
    restart: unless-stopped
    ports:
      - ${SJS_ADMIN_PORT:-8055}:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./scripts/init-directus.sh:/docker-entrypoint.d/init-directus.sh
    depends_on:
      admin-cache:
        condition: service_healthy
    environment:
      ADMIN_EMAIL: ${SJS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${SJS_ADMIN_PASSWORD}
      ADMIN_TOKEN: ${SJS_ADMIN_TOKEN}
      SECRET: ${SJS_ADMIN_SECRET}
      WEBHOOK_SECRET: ${SJS_WEBHOOK_SECRET}
      PUBLIC_URL: ${SJS_ADMIN_URL_DOCKER:-http://admin:8055}

      # Database settings:
      DB_CLIENT: ${SJS_DB_CLIENT:-pg}
      DB_HOST: ${SJS_DB_HOST_DOCKER:-database}
      DB_PORT: 5432
      DB_DATABASE: ${SJS_DB_DATABASE}
      DB_USER: ${SJS_DB_USER}
      DB_PASSWORD: ${SJS_DB_PASSWORD}
      DB_SSL: ${SJS_DB_SSL}
      # DB_CONNECTION_TIMEOUT: 60000
      # DB_ACQUIRE_CONNECTION_TIMEOUT: 60000

      # Cache settings:
      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: redis
      REDIS: redis://admin-cache:6379
  admin-cache:
    image: redis:6
    healthcheck:
      test:
        - CMD-SHELL
        - '[ $$(redis-cli ping) = ''PONG'' ]'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
