#!/bin/bash
#
# Creates a dev seed SQL file with essential tables only.
# This is used by dev:reset to populate a fresh database.
#
# Includes:
# - User/auth tables (user, account)
# - Profile and all related content
# - Job configuration (searches, preferences, platforms)
# - Referenced files only
#
# Excludes:
# - Sessions, logs, generated content
# - Jobs, job matches, applications
# - AI chat history
#

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="$DIR/../db-dumps"
OUTPUT_FILE="$OUTPUT_DIR/dev-seed.sql"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

echo "Creating dev seed..."
echo ""

# Tables to include (order matters for FK dependencies)
TABLES=(
  # Auth
  "user"
  account
  # Profile core
  profiles
  # Work experience
  work_experiences
  work_experience_achievements
  work_experience_technologies
  work_experience_projects
  work_experience_project_technologies
  # Education & skills
  education
  tech_skill_categories
  tech_skills
  tech_skill_types
  # Side projects
  side_projects
  side_project_achievements
  side_project_technologies
  # Other profile data
  languages
  highlights
  os_contributions
  "references"
  project_stories
  salary_expectations
  cheat_sheets
  collected_data
  # Profile versions
  profile_versions
  profile_version_extensions
  # Job config
  job_platforms
  job_searches
  job_searches_job_sites
  job_match_preferences
  platform_profiles
  # AI templates
  ai_chat_templates
)

# Start the seed file
cat > "$OUTPUT_FILE" << 'EOF'
--
-- Dev Seed Data
-- Generated by create-dev-seed.sh
--
-- This file contains only essential data for development.
-- Schema is managed by Prisma (prisma db push).
--

-- Disable FK constraint triggers during restore
SET session_replication_role = 'replica';

EOF

# Step 1: Export referenced directus_folders and directus_files
echo "  [1/3] Exporting referenced files..."

# Get all referenced file UUIDs
FILE_UUIDS=$(psql -U postgres -d smartjobseeker -t -A -c "
SELECT DISTINCT id FROM (
  SELECT profile_picture AS id FROM profiles WHERE profile_picture IS NOT NULL
  UNION SELECT source_cv AS id FROM profiles WHERE source_cv IS NOT NULL
  UNION SELECT logo AS id FROM work_experiences WHERE logo IS NOT NULL
  UNION SELECT logo AS id FROM education WHERE logo IS NOT NULL
) AS files WHERE id IS NOT NULL;
")

if [ -n "$FILE_UUIDS" ]; then
  # Get folder UUIDs for these files
  FOLDER_UUIDS=$(psql -U postgres -d smartjobseeker -t -A -c "
  SELECT DISTINCT folder FROM directus_files
  WHERE id IN ('$(echo "$FILE_UUIDS" | tr '\n' "'" | sed "s/'/','/g" | sed "s/,'$//")')
  AND folder IS NOT NULL;
  ")

  # Export folders first (if any)
  if [ -n "$FOLDER_UUIDS" ]; then
    echo "        - Exporting directus_folders..."
    {
      echo "-- Referenced directus_folders"
      echo "COPY public.directus_folders FROM stdin WITH (FORMAT csv, NULL 'NULL_VALUE');"
      psql -U postgres -d smartjobseeker -c "
      COPY (
        SELECT * FROM directus_folders
        WHERE id IN ('$(echo "$FOLDER_UUIDS" | tr '\n' "'" | sed "s/'/','/g" | sed "s/,'$//")')
      ) TO STDOUT WITH (FORMAT csv, NULL 'NULL_VALUE')
      "
      echo "\\."
      echo ""
    } >> "$OUTPUT_FILE"
  fi

  # Export files
  echo "        - Exporting directus_files..."
  {
    echo "-- Referenced directus_files"
    echo "COPY public.directus_files FROM stdin WITH (FORMAT csv, NULL 'NULL_VALUE');"
    psql -U postgres -d smartjobseeker -c "
    COPY (
      SELECT * FROM directus_files
      WHERE id IN ('$(echo "$FILE_UUIDS" | tr '\n' "'" | sed "s/'/','/g" | sed "s/,'$//")')
    ) TO STDOUT WITH (FORMAT csv, NULL 'NULL_VALUE')
    "
    echo "\\."
    echo ""
  } >> "$OUTPUT_FILE"
else
  echo "        - No files referenced"
fi

# Step 2: Export each table
echo ""
echo "  [2/3] Exporting tables..."

for table in "${TABLES[@]}"; do
  # Check if table has data
  count=$(psql -U postgres -d smartjobseeker -t -A -c "SELECT COUNT(*) FROM \"$table\";")

  if [ "$count" -gt 0 ]; then
    echo "        - $table ($count rows)"
    {
      echo "-- $table"
      echo "COPY public.\"$table\" FROM stdin WITH (FORMAT csv, NULL 'NULL_VALUE');"
      psql -U postgres -d smartjobseeker -c "COPY public.\"$table\" TO STDOUT WITH (FORMAT csv, NULL 'NULL_VALUE')"
      echo "\\."
      echo ""
    } >> "$OUTPUT_FILE"
  else
    echo "        - $table (empty, skipped)"
  fi
done

# Step 3: Reset sequences and re-enable FK triggers
echo ""
echo "  [3/3] Adding sequence resets..."

{
  echo "-- Re-enable FK constraint triggers"
  echo "SET session_replication_role = 'origin';"
  echo ""
  echo "-- Reset sequences to max ID + 1"
} >> "$OUTPUT_FILE"

# Reset sequences for tables with auto-increment IDs
SEQUENCE_TABLES=(
  profiles
  work_experiences
  work_experience_achievements
  work_experience_technologies
  work_experience_projects
  work_experience_project_technologies
  education
  tech_skill_categories
  tech_skills
  tech_skill_types
  side_projects
  side_project_achievements
  side_project_technologies
  languages
  highlights
  os_contributions
  "references"
  project_stories
  salary_expectations
  cheat_sheets
  collected_data
  profile_versions
  profile_version_extensions
  job_platforms
  job_searches
  job_searches_job_sites
  job_match_preferences
  platform_profiles
  ai_chat_templates
)

for table in "${SEQUENCE_TABLES[@]}"; do
  echo "SELECT setval('public.${table}_id_seq', COALESCE((SELECT MAX(id) FROM public.\"$table\"), 1));" >> "$OUTPUT_FILE"
done

# Get file size
SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  Dev seed created: db-dumps/dev-seed.sql ($SIZE)"
echo "═══════════════════════════════════════════════════════"
