#!/bin/bash
#
# Creates a dev seed SQL file with essential tables only.
# This is used by dev:reset to populate a fresh database.
#
# Includes:
# - Directus config (schema, roles, permissions, flows)
# - User/auth tables (user, account)
# - Profile and all related content
# - Job configuration (searches, preferences, platforms)
# - Referenced files only
#
# Excludes:
# - Sessions, logs, generated content
# - Jobs, job matches, applications
# - AI chat history
# - Directus audit/activity tables
#

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="$DIR/../db-dumps"
OUTPUT_FILE="$OUTPUT_DIR/dev-seed.sql"

# Database connection settings (supports both local and containerized environments)
DB_HOST="${SJS_DB_HOST:-localhost}"
DB_USER="${SJS_DB_USER:-postgres}"
DB_NAME="${SJS_DB_DATABASE:-smartjobseeker}"
DB_PASSWORD="${SJS_DB_PASSWORD:-postgres}"

# Helper for psql commands
db_query() {
  PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" "$@"
}

# Helper for pg_dump
db_dump() {
  PGPASSWORD="$DB_PASSWORD" pg_dump -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" "$@"
}

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

echo "Creating dev seed..."
echo ""

# Directus config tables (order matters for FK dependencies)
DIRECTUS_TABLES=(
  # Migrations (MUST be first - tells Directus DB is already initialized)
  directus_migrations
  # Files (needed early, referenced by other tables)
  directus_folders
  directus_files
  # Schema configuration
  directus_collections
  directus_fields
  directus_relations
  # Roles and policies (no FK deps)
  directus_roles
  directus_policies
  # Users (before access, since access references users)
  directus_users
  # Access links roles/users to policies
  directus_access
  directus_permissions
  # Settings
  directus_settings
  directus_translations
  # Automation
  directus_flows
  directus_operations
)

# Application tables (order matters for FK dependencies)
TABLES=(
  # Auth
  "user"
  account
  # Profile core
  profiles
  # Work experience
  work_experiences
  work_experience_achievements
  work_experience_technologies
  work_experience_projects
  work_experience_project_technologies
  # Education & skills
  education
  tech_skill_categories
  tech_skills
  tech_skill_types
  # Side projects
  side_projects
  side_project_achievements
  side_project_technologies
  # Other profile data
  languages
  highlights
  os_contributions
  "references"
  project_stories
  salary_expectations
  cheat_sheets
  collected_data
  # Profile versions
  profile_versions
  profile_version_extensions
  # Job config
  job_platforms
  job_searches
  job_searches_job_sites
  job_match_preferences
  platform_profiles
  # AI templates
  ai_chat_templates
)

# Start the seed file
cat > "$OUTPUT_FILE" << 'EOF'
--
-- Dev Seed Data
-- Generated by create-dev-seed.sh
--
-- This file contains only essential data for development.
-- Schema is managed by Prisma (prisma db push).
--

-- Disable FK constraint triggers during restore
SET session_replication_role = 'replica';

EOF

# Step 1: Export Directus tables WITH SCHEMA (so they can be created before Directus starts)
echo "  [1/3] Exporting Directus config (with schema)..."

# Build table list for pg_dump
DIRECTUS_TABLE_ARGS=""
for table in "${DIRECTUS_TABLES[@]}"; do
  DIRECTUS_TABLE_ARGS="$DIRECTUS_TABLE_ARGS -t $table"
done

# Dump Directus tables with schema and data
echo "        - Dumping Directus tables with schema..."
db_dump \
  --no-owner --no-acl \
  --disable-triggers \
  $DIRECTUS_TABLE_ARGS \
  >> "$OUTPUT_FILE"

# Count what was exported
for table in "${DIRECTUS_TABLES[@]}"; do
  exists=$(db_query -t -A -c "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '$table');")
  if [ "$exists" = "t" ]; then
    count=$(db_query -t -A -c "SELECT COUNT(*) FROM \"$table\";")
    echo "        - $table ($count rows)"
  fi
done

# Step 2: Export application tables WITH SCHEMA
echo ""
echo "  [2/3] Exporting application tables (with schema)..."

# Tables to EXCLUDE (everything not in TABLES list + directus tables which are already dumped)
EXCLUDE_TABLES=(
  # Already dumped Directus tables
  directus_migrations directus_folders directus_files directus_collections directus_fields
  directus_relations directus_roles directus_policies directus_users directus_access
  directus_permissions directus_settings directus_translations directus_flows directus_operations
  # Other Directus tables not needed
  directus_activity directus_revisions directus_sessions directus_notifications
  directus_presets directus_dashboards directus_panels directus_shares directus_versions
  directus_comments directus_extensions directus_deployments directus_deployment_projects
  directus_deployment_runs
  # App tables not needed
  session verification
  jobs job_matches job_statuses job_resources applications application_questions application_letters
  application_activity_log applications_files
  profile_exports profile_tokens
  ai_chats ai_prompts config
)

# Build exclude args
EXCLUDE_ARGS=""
for table in "${EXCLUDE_TABLES[@]}"; do
  EXCLUDE_ARGS="$EXCLUDE_ARGS --exclude-table=$table"
done

# Dump remaining tables (app tables we want) with schema and data
echo "        - Dumping application tables with schema..."
db_dump \
  --no-owner --no-acl \
  --disable-triggers \
  $EXCLUDE_ARGS >> "$OUTPUT_FILE"

# Count what was exported
for table in "${TABLES[@]}"; do
  count=$(db_query -t -A -c "SELECT COUNT(*) FROM \"$table\";")
  if [ "$count" -gt 0 ]; then
    echo "        - $table ($count rows)"
  else
    echo "        - $table (empty)"
  fi
done

# Step 3: Re-enable FK triggers (pg_dump handles sequences)
echo ""
echo "  [3/3] Finalizing..."

{
  echo ""
  echo "-- Re-enable FK constraint triggers"
  echo "SET session_replication_role = 'origin';"
} >> "$OUTPUT_FILE"

# Get file size
SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  Dev seed created: db-dumps/dev-seed.sql ($SIZE)"
echo "═══════════════════════════════════════════════════════"
